apiVersion: v1
kind: Namespace
metadata:
  name: qa

---

apiVersion: v1
kind: Pod
metadata:
  name: qa-test-pod
  namespace: qa
  labels:
    app: qa-test-pod
spec:
  containers:
    - name: qa-test-container
      image: busybox
      command:
        - sh
        - -c
      args:
        - |
          while true; do
            echo -e "Testing connectivity...\n\n"
            if wget -T 3 -qO- http://pizza-ordering-sys-svc.default.svc.cluster.local; then
              echo -e "\n==================== Connection Allowed ====================== \n"
            else
              echo "\n==================== Blocked by NetworkPolicy ====================== \n"
            fi
            sleep 5
          done
