apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-pv-0
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/apache2/htdocs
    type: DirectoryOrCreate
  storageClassName: htdocs-sc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-pv-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/apache2/htdocs
    type: DirectoryOrCreate
  storageClassName: htdocs-sc

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-pv-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/apache2/htdocs
    type: DirectoryOrCreate
  storageClassName: htdocs-sc

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-pv-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/apache2/htdocs
    type: DirectoryOrCreate
  storageClassName: htdocs-sc

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: htdocs-pv-4
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /usr/local/apache2/htdocs
    type: DirectoryOrCreate
  storageClassName: htdocs-sc


