apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pizza-ordering-sys
  labels:
    app: pizza-ordering-sys
spec:
  serviceName: pizza-ordering-sys-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: pizza-ordering-sys
  template:
    metadata:
      labels:
        app: pizza-ordering-sys
    spec:
      restartPolicy: Always
      containers:
        - name: pizza-ordering-sys-container
          image: liteshz/pizza-paradise:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: htdocs-data
              mountPath: /usr/local/apache2/htdocs
      initContainers:
        - name: busybox
          image: busybox:latest
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh 
            - -c
          args:
            - |
              mkdir -p /usr/local/apache2/htdocs/host
              echo "Running Pod IP: ${POD_IP}" > /usr/local/apache2/htdocs/host/index.html
          volumeMounts:
            - name: htdocs-data
              mountPath: /usr/local/apache2/htdocs
  volumeClaimTemplates:
    - metadata:
        name: htdocs-data
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: htdocs-sc

---

apiVersion: v1
kind: Service
metadata:
  name: pizza-ordering-sys-headless-svc
spec:
  clusterIP: None
  selector:
    app: pizza-ordering-sys
  ports:
    - name: http
      port: 80
      targetPort: 80
